name: Metrics

on:
  schedule: [{ cron: "0 */12 * * *" }]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: GivaldoMedeirosNeto
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          config_theme: dracula
          config_display: large
          config_timezone: America/Sao_Paulo

          base: header, activity, community

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used

          plugin_stars: no
          plugin_followup: no
          plugin_repositories: no
          plugin_isocalendar: no
